In [1]:
# IST652 - Mini Project 2 - Aidan Surowiec - asurowie
# 5/18/21

In [2]:
# This mini project is going to compare the twitter data of Netflix and Hulu - I will be answering three comparison questions
# I did use this link as a reference for some of my code to convert to a data frame 
    # https://github.com/RodolfoFerro/pandas_twitter/blob/master/01-extracting-data.md

# The data was retrieved from the official accounts of Hulu and Netflix through the twitter API

# Question 1: How do the likes, retweet , and length statistics compare between the most recent 600 tweets?
# Question 2: Of the last 600 tweets, how does the tweet distribution per hour differ between the two?
# Question 3: How does the source of tweet creation differ between the two? What does distribution looks like, and how does engagement correlate?

In [3]:
#Install tweepy directly to Jupyter Notebook
#I installed in my Anaconda Command prompt but tweepy would not run without this line of code 
!pip install tweepy

Requirement already satisfied: tweepy in c:\users\aidan\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: six>=1.10.0 in c:\users\aidan\anaconda3\lib\site-packages (from tweepy) (1.15.0)
Requirement already satisfied: requests[socks]>=2.11.1 in c:\users\aidan\anaconda3\lib\site-packages (from tweepy) (2.24.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\aidan\anaconda3\lib\site-packages (from tweepy) (1.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\aidan\anaconda3\lib\site-packages (from requests[socks]>=2.11.1->tweepy) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\aidan\anaconda3\lib\site-packages (from requests[socks]>=2.11.1->tweepy) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\aidan\anaconda3\lib\site-packages (from requests[socks]>=2.11.1->tweepy) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\aidan\anaconda3\lib\site-packages (from requests[socks]>=2.11.1->tweepy) (1.25.11)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in c:\users\aidan\anaconda3\lib\site-packages (from requests[socks]>=2.11.1->tweepy) (1.7.1)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\aidan\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->tweepy) (3.1.0)

In [4]:
#import tweepy and json to be able to use API tools in JSON data format 
import tweepy
import json

In [5]:
#Create variables for the 4 OAuth keys necessary to access the twitter API

#API Keys
CONSUMER_KEY = 'ZW0t2yu21eqEQPnWJqnpqqVo7'
CONSUMER_SECRET = 'BXtZ17mE4aYDXBC2eil1xdinHvESanAMnDKSy7OvGpL7mUvUGi'

#Access Tokens
OAUTH_TOKEN = '1377006615929454595-9b3TWN3ndUPP9by1aVIGXhOmf2WiCo'
OAUTH_SECRET = 'OCcPvA4L9t6oWDLDejvdvu1ZlUq2tha7pby6SdO3e7kNb'

In [6]:
#Run the authorization commands to twitter with the OAuth variables created in the step above 

auth = tweepy.OAuthHandler(CONSUMER_KEY,CONSUMER_SECRET)
auth.set_access_token(OAUTH_TOKEN,OAUTH_SECRET)
api = tweepy.API(auth)

In [7]:
#Check to see if API is defined to ensure authorization has been approved and credentials have been accepted 
type(api)

tweepy.api.API

In [8]:
#Get the user timeline data from Netflix - getting the tweets from the verified Netflix account 

netflix_timeline = api.user_timeline('netflix', count=10)
type(netflix_timeline)

tweepy.models.ResultSet

In [9]:
#Turn the API call into a list - ensure there are 10 tweets
netflix_list = list(netflix_timeline)
len(netflix_list)

10

In [10]:
#Check the type of the first tweet - instead of ResultSet - should be the Status of one tweet
type(netflix_list[0])

tweepy.models.Status

In [11]:
#Return the first instance in our list from the API call - look how messy it is 
netflix_list[0]

Status(_api=<tweepy.api.API object at 0x0000020CB63F86D0>, _json={'created_at': 'Wed May 19 23:52:51 +0000 2021', 'id': 1395165585311375360, 'id_str': '1395165585311375360', 'text': 'Who Killed Sara?\n\nSeason 2 is now on Netflix. https://t.co/9L8tiCY2EU', 'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 1395165559361216513, 'id_str': '1395165559361216513', 'indices': [46, 69], 'media_url': 'http://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg', 'media_url_https': 'https://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg', 'url': 'https://t.co/9L8tiCY2EU', 'display_url': 'pic.twitter.com/9L8tiCY2EU', 'expanded_url': 'https://twitter.com/netflix/status/1395165585311375360/photo/1', 'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 680, 'h': 360, 'resize': 'fit'}, 'large': {'w': 1670, 'h': 884, 'resize': 'fit'}, 'medium': {'w': 1200, 'h': 635, 'resize': 'fit'}}}]}, 'extended_entities': {'media': [{'id': 1395165559361216513, 'id_str': '1395165559361216513', 'indices': [46, 69], 'media_url': 'http://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg', 'media_url_https': 'https://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg', 'url': 'https://t.co/9L8tiCY2EU', 'display_url': 'pic.twitter.com/9L8tiCY2EU', 'expanded_url': 'https://twitter.com/netflix/status/1395165585311375360/photo/1', 'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 680, 'h': 360, 'resize': 'fit'}, 'large': {'w': 1670, 'h': 884, 'resize': 'fit'}, 'medium': {'w': 1200, 'h': 635, 'resize': 'fit'}}}, {'id': 1395165559361212417, 'id_str': '1395165559361212417', 'indices': [46, 69], 'media_url': 'http://pbs.twimg.com/media/E1yfrzCVkAEYtZ2.jpg', 'media_url_https': 'https://pbs.twimg.com/media/E1yfrzCVkAEYtZ2.jpg', 'url': 'https://t.co/9L8tiCY2EU', 'display_url': 'pic.twitter.com/9L8tiCY2EU', 'expanded_url': 'https://twitter.com/netflix/status/1395165585311375360/photo/1', 'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'medium': {'w': 1200, 'h': 613, 'resize': 'fit'}, 'large': {'w': 1798, 'h': 918, 'resize': 'fit'}, 'small': {'w': 680, 'h': 347, 'resize': 'fit'}}}, {'id': 1395165559369601025, 'id_str': '1395165559369601025', 'indices': [46, 69], 'media_url': 'http://pbs.twimg.com/media/E1yfrzEVkAEBFSL.jpg', 'media_url_https': 'https://pbs.twimg.com/media/E1yfrzEVkAEBFSL.jpg', 'url': 'https://t.co/9L8tiCY2EU', 'display_url': 'pic.twitter.com/9L8tiCY2EU', 'expanded_url': 'https://twitter.com/netflix/status/1395165585311375360/photo/1', 'type': 'photo', 'sizes': {'small': {'w': 680, 'h': 355, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'medium': {'w': 1200, 'h': 627, 'resize': 'fit'}, 'large': {'w': 1734, 'h': 906, 'resize': 'fit'}}}, {'id': 1395165559377981442, 'id_str': '1395165559377981442', 'indices': [46, 69], 'media_url': 'http://pbs.twimg.com/media/E1yfrzGVcAIQGcR.jpg', 'media_url_https': 'https://pbs.twimg.com/media/E1yfrzGVcAIQGcR.jpg', 'url': 'https://t.co/9L8tiCY2EU', 'display_url': 'pic.twitter.com/9L8tiCY2EU', 'expanded_url': 'https://twitter.com/netflix/status/1395165585311375360/photo/1', 'type': 'photo', 'sizes': {'small': {'w': 680, 'h': 340, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'large': {'w': 1822, 'h': 912, 'resize': 'fit'}, 'medium': {'w': 1200, 'h': 601, 'resize': 'fit'}}}]}, 'source': '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 16573941, 'id_str': '16573941', 'name': 'Netflix', 'screen_name': 'netflix', 'location': 'California, USA', 'description': 'Meet Asian Americans & Pacific Islanders who are defining their stories — on their terms — with this collection https://t.co/2gcE1B3nHk', 'url': 'https://t.co/XzOdAb0vdS', 'entities': {'url': {'urls': [{'url': 'https://t.co/XzOdAb0vdS', 'expanded_url': 'http://netflix.com/blacklivesmatter', 'display_url': 'netflix.com/blacklivesmatt…', 'indices': [0, 23]}]}, 'description': {'urls': [{'url': 'https://t.co/2gcE1B3nHk', 'expanded_url': 'https://www.netflix.com/browse/genre/3137292', 'display_url': 'netflix.com/browse/genre/3…', 'indices': [112, 135]}]}}, 'protected': False, 'followers_count': 11891956, 'friends_count': 1797, 'listed_count': 17687, 'created_at': 'Fri Oct 03 04:16:17 +0000 2008', 'favourites_count': 14985, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 38916, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'C0DEED', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/16573941/1621037719', 'profile_link_color': 'E50914', 'profile_sidebar_border_color': 'FFFFFF', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': False, 'has_extended_profile': False, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 180, 'favorite_count': 1868, 'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'lang': 'en'}, created_at=datetime.datetime(2021, 5, 19, 23, 52, 51), id=1395165585311375360, id_str='1395165585311375360', text='Who Killed Sara?\n\nSeason 2 is now on Netflix. https://t.co/9L8tiCY2EU', truncated=False, entities={'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [], 'media': [{'id': 1395165559361216513, 'id_str': '1395165559361216513', 'indices': [46, 69], 'media_url': 'http://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg', 'media_url_https': 'https://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg', 'url': 'https://t.co/9L8tiCY2EU', 'display_url': 'pic.twitter.com/9L8tiCY2EU', 'expanded_url': 'https://twitter.com/netflix/status/1395165585311375360/photo/1', 'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 680, 'h': 360, 'resize': 'fit'}, 'large': {'w': 1670, 'h': 884, 'resize': 'fit'}, 'medium': {'w': 1200, 'h': 635, 'resize': 'fit'}}}]}, extended_entities={'media': [{'id': 1395165559361216513, 'id_str': '1395165559361216513', 'indices': [46, 69], 'media_url': 'http://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg', 'media_url_https': 'https://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg', 'url': 'https://t.co/9L8tiCY2EU', 'display_url': 'pic.twitter.com/9L8tiCY2EU', 'expanded_url': 'https://twitter.com/netflix/status/1395165585311375360/photo/1', 'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'small': {'w': 680, 'h': 360, 'resize': 'fit'}, 'large': {'w': 1670, 'h': 884, 'resize': 'fit'}, 'medium': {'w': 1200, 'h': 635, 'resize': 'fit'}}}, {'id': 1395165559361212417, 'id_str': '1395165559361212417', 'indices': [46, 69], 'media_url': 'http://pbs.twimg.com/media/E1yfrzCVkAEYtZ2.jpg', 'media_url_https': 'https://pbs.twimg.com/media/E1yfrzCVkAEYtZ2.jpg', 'url': 'https://t.co/9L8tiCY2EU', 'display_url': 'pic.twitter.com/9L8tiCY2EU', 'expanded_url': 'https://twitter.com/netflix/status/1395165585311375360/photo/1', 'type': 'photo', 'sizes': {'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'medium': {'w': 1200, 'h': 613, 'resize': 'fit'}, 'large': {'w': 1798, 'h': 918, 'resize': 'fit'}, 'small': {'w': 680, 'h': 347, 'resize': 'fit'}}}, {'id': 1395165559369601025, 'id_str': '1395165559369601025', 'indices': [46, 69], 'media_url': 'http://pbs.twimg.com/media/E1yfrzEVkAEBFSL.jpg', 'media_url_https': 'https://pbs.twimg.com/media/E1yfrzEVkAEBFSL.jpg', 'url': 'https://t.co/9L8tiCY2EU', 'display_url': 'pic.twitter.com/9L8tiCY2EU', 'expanded_url': 'https://twitter.com/netflix/status/1395165585311375360/photo/1', 'type': 'photo', 'sizes': {'small': {'w': 680, 'h': 355, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'medium': {'w': 1200, 'h': 627, 'resize': 'fit'}, 'large': {'w': 1734, 'h': 906, 'resize': 'fit'}}}, {'id': 1395165559377981442, 'id_str': '1395165559377981442', 'indices': [46, 69], 'media_url': 'http://pbs.twimg.com/media/E1yfrzGVcAIQGcR.jpg', 'media_url_https': 'https://pbs.twimg.com/media/E1yfrzGVcAIQGcR.jpg', 'url': 'https://t.co/9L8tiCY2EU', 'display_url': 'pic.twitter.com/9L8tiCY2EU', 'expanded_url': 'https://twitter.com/netflix/status/1395165585311375360/photo/1', 'type': 'photo', 'sizes': {'small': {'w': 680, 'h': 340, 'resize': 'fit'}, 'thumb': {'w': 150, 'h': 150, 'resize': 'crop'}, 'large': {'w': 1822, 'h': 912, 'resize': 'fit'}, 'medium': {'w': 1200, 'h': 601, 'resize': 'fit'}}}]}, source='TweetDeck', source_url='https://about.twitter.com/products/tweetdeck', in_reply_to_status_id=None, in_reply_to_status_id_str=None, in_reply_to_user_id=None, in_reply_to_user_id_str=None, in_reply_to_screen_name=None, author=User(_api=<tweepy.api.API object at 0x0000020CB63F86D0>, _json={'id': 16573941, 'id_str': '16573941', 'name': 'Netflix', 'screen_name': 'netflix', 'location': 'California, USA', 'description': 'Meet Asian Americans & Pacific Islanders who are defining their stories — on their terms — with this collection https://t.co/2gcE1B3nHk', 'url': 'https://t.co/XzOdAb0vdS', 'entities': {'url': {'urls': [{'url': 'https://t.co/XzOdAb0vdS', 'expanded_url': 'http://netflix.com/blacklivesmatter', 'display_url': 'netflix.com/blacklivesmatt…', 'indices': [0, 23]}]}, 'description': {'urls': [{'url': 'https://t.co/2gcE1B3nHk', 'expanded_url': 'https://www.netflix.com/browse/genre/3137292', 'display_url': 'netflix.com/browse/genre/3…', 'indices': [112, 135]}]}}, 'protected': False, 'followers_count': 11891956, 'friends_count': 1797, 'listed_count': 17687, 'created_at': 'Fri Oct 03 04:16:17 +0000 2008', 'favourites_count': 14985, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 38916, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'C0DEED', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/16573941/1621037719', 'profile_link_color': 'E50914', 'profile_sidebar_border_color': 'FFFFFF', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': False, 'has_extended_profile': False, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, id=16573941, id_str='16573941', name='Netflix', screen_name='netflix', location='California, USA', description='Meet Asian Americans & Pacific Islanders who are defining their stories — on their terms — with this collection https://t.co/2gcE1B3nHk', url='https://t.co/XzOdAb0vdS', entities={'url': {'urls': [{'url': 'https://t.co/XzOdAb0vdS', 'expanded_url': 'http://netflix.com/blacklivesmatter', 'display_url': 'netflix.com/blacklivesmatt…', 'indices': [0, 23]}]}, 'description': {'urls': [{'url': 'https://t.co/2gcE1B3nHk', 'expanded_url': 'https://www.netflix.com/browse/genre/3137292', 'display_url': 'netflix.com/browse/genre/3…', 'indices': [112, 135]}]}}, protected=False, followers_count=11891956, friends_count=1797, listed_count=17687, created_at=datetime.datetime(2008, 10, 3, 4, 16, 17), favourites_count=14985, utc_offset=None, time_zone=None, geo_enabled=True, verified=True, statuses_count=38916, lang=None, contributors_enabled=False, is_translator=False, is_translation_enabled=False, profile_background_color='C0DEED', profile_background_image_url='http://abs.twimg.com/images/themes/theme1/bg.png', profile_background_image_url_https='https://abs.twimg.com/images/themes/theme1/bg.png', profile_background_tile=False, profile_image_url='http://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg', profile_image_url_https='https://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg', profile_banner_url='https://pbs.twimg.com/profile_banners/16573941/1621037719', profile_link_color='E50914', profile_sidebar_border_color='FFFFFF', profile_sidebar_fill_color='DDEEF6', profile_text_color='333333', profile_use_background_image=False, has_extended_profile=False, default_profile=False, default_profile_image=False, following=False, follow_request_sent=False, notifications=False, translator_type='none', withheld_in_countries=[]), user=User(_api=<tweepy.api.API object at 0x0000020CB63F86D0>, _json={'id': 16573941, 'id_str': '16573941', 'name': 'Netflix', 'screen_name': 'netflix', 'location': 'California, USA', 'description': 'Meet Asian Americans & Pacific Islanders who are defining their stories — on their terms — with this collection https://t.co/2gcE1B3nHk', 'url': 'https://t.co/XzOdAb0vdS', 'entities': {'url': {'urls': [{'url': 'https://t.co/XzOdAb0vdS', 'expanded_url': 'http://netflix.com/blacklivesmatter', 'display_url': 'netflix.com/blacklivesmatt…', 'indices': [0, 23]}]}, 'description': {'urls': [{'url': 'https://t.co/2gcE1B3nHk', 'expanded_url': 'https://www.netflix.com/browse/genre/3137292', 'display_url': 'netflix.com/browse/genre/3…', 'indices': [112, 135]}]}}, 'protected': False, 'followers_count': 11891956, 'friends_count': 1797, 'listed_count': 17687, 'created_at': 'Fri Oct 03 04:16:17 +0000 2008', 'favourites_count': 14985, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': True, 'statuses_count': 38916, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'C0DEED', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/16573941/1621037719', 'profile_link_color': 'E50914', 'profile_sidebar_border_color': 'FFFFFF', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': False, 'has_extended_profile': False, 'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, id=16573941, id_str='16573941', name='Netflix', screen_name='netflix', location='California, USA', description='Meet Asian Americans & Pacific Islanders who are defining their stories — on their terms — with this collection https://t.co/2gcE1B3nHk', url='https://t.co/XzOdAb0vdS', entities={'url': {'urls': [{'url': 'https://t.co/XzOdAb0vdS', 'expanded_url': 'http://netflix.com/blacklivesmatter', 'display_url': 'netflix.com/blacklivesmatt…', 'indices': [0, 23]}]}, 'description': {'urls': [{'url': 'https://t.co/2gcE1B3nHk', 'expanded_url': 'https://www.netflix.com/browse/genre/3137292', 'display_url': 'netflix.com/browse/genre/3…', 'indices': [112, 135]}]}}, protected=False, followers_count=11891956, friends_count=1797, listed_count=17687, created_at=datetime.datetime(2008, 10, 3, 4, 16, 17), favourites_count=14985, utc_offset=None, time_zone=None, geo_enabled=True, verified=True, statuses_count=38916, lang=None, contributors_enabled=False, is_translator=False, is_translation_enabled=False, profile_background_color='C0DEED', profile_background_image_url='http://abs.twimg.com/images/themes/theme1/bg.png', profile_background_image_url_https='https://abs.twimg.com/images/themes/theme1/bg.png', profile_background_tile=False, profile_image_url='http://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg', profile_image_url_https='https://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg', profile_banner_url='https://pbs.twimg.com/profile_banners/16573941/1621037719', profile_link_color='E50914', profile_sidebar_border_color='FFFFFF', profile_sidebar_fill_color='DDEEF6', profile_text_color='333333', profile_use_background_image=False, has_extended_profile=False, default_profile=False, default_profile_image=False, following=False, follow_request_sent=False, notifications=False, translator_type='none', withheld_in_countries=[]), geo=None, coordinates=None, place=None, contributors=None, is_quote_status=False, retweet_count=180, favorite_count=1868, favorited=False, retweeted=False, possibly_sensitive=False, lang='en')

In [12]:
#Convert the first tweet in netflix list to a json type so that we can use json.dumps to analyze the returned content 
tweet_json = netflix_list[0]._json

#Check the type to ensure that it is a dictionary 
type(tweet_json)

dict

In [13]:
#Use json dumps to look at all the content returned in the first tweet grabbed from the newly formed list 
#Each variable can be seen - we can see what would be useful to include in a data frame 
print(json.dumps(tweet_json, indent=2))

{
  "created_at": "Wed May 19 23:52:51 +0000 2021",
  "id": 1395165585311375360,
  "id_str": "1395165585311375360",
  "text": "Who Killed Sara?\n\nSeason 2 is now on Netflix. https://t.co/9L8tiCY2EU",
  "truncated": false,
  "entities": {
    "hashtags": [],
    "symbols": [],
    "user_mentions": [],
    "urls": [],
    "media": [
      {
        "id": 1395165559361216513,
        "id_str": "1395165559361216513",
        "indices": [
          46,
          69
        ],
        "media_url": "http://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg",
        "media_url_https": "https://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg",
        "url": "https://t.co/9L8tiCY2EU",
        "display_url": "pic.twitter.com/9L8tiCY2EU",
        "expanded_url": "https://twitter.com/netflix/status/1395165585311375360/photo/1",
        "type": "photo",
        "sizes": {
          "thumb": {
            "w": 150,
            "h": 150,
            "resize": "crop"
          },
          "small": {
            "w": 680,
            "h": 360,
            "resize": "fit"
          },
          "large": {
            "w": 1670,
            "h": 884,
            "resize": "fit"
          },
          "medium": {
            "w": 1200,
            "h": 635,
            "resize": "fit"
          }
        }
      }
    ]
  },
  "extended_entities": {
    "media": [
      {
        "id": 1395165559361216513,
        "id_str": "1395165559361216513",
        "indices": [
          46,
          69
        ],
        "media_url": "http://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg",
        "media_url_https": "https://pbs.twimg.com/media/E1yfrzCVoAEtlyh.jpg",
        "url": "https://t.co/9L8tiCY2EU",
        "display_url": "pic.twitter.com/9L8tiCY2EU",
        "expanded_url": "https://twitter.com/netflix/status/1395165585311375360/photo/1",
        "type": "photo",
        "sizes": {
          "thumb": {
            "w": 150,
            "h": 150,
            "resize": "crop"
          },
          "small": {
            "w": 680,
            "h": 360,
            "resize": "fit"
          },
          "large": {
            "w": 1670,
            "h": 884,
            "resize": "fit"
          },
          "medium": {
            "w": 1200,
            "h": 635,
            "resize": "fit"
          }
        }
      },
      {
        "id": 1395165559361212417,
        "id_str": "1395165559361212417",
        "indices": [
          46,
          69
        ],
        "media_url": "http://pbs.twimg.com/media/E1yfrzCVkAEYtZ2.jpg",
        "media_url_https": "https://pbs.twimg.com/media/E1yfrzCVkAEYtZ2.jpg",
        "url": "https://t.co/9L8tiCY2EU",
        "display_url": "pic.twitter.com/9L8tiCY2EU",
        "expanded_url": "https://twitter.com/netflix/status/1395165585311375360/photo/1",
        "type": "photo",
        "sizes": {
          "thumb": {
            "w": 150,
            "h": 150,
            "resize": "crop"
          },
          "medium": {
            "w": 1200,
            "h": 613,
            "resize": "fit"
          },
          "large": {
            "w": 1798,
            "h": 918,
            "resize": "fit"
          },
          "small": {
            "w": 680,
            "h": 347,
            "resize": "fit"
          }
        }
      },
      {
        "id": 1395165559369601025,
        "id_str": "1395165559369601025",
        "indices": [
          46,
          69
        ],
        "media_url": "http://pbs.twimg.com/media/E1yfrzEVkAEBFSL.jpg",
        "media_url_https": "https://pbs.twimg.com/media/E1yfrzEVkAEBFSL.jpg",
        "url": "https://t.co/9L8tiCY2EU",
        "display_url": "pic.twitter.com/9L8tiCY2EU",
        "expanded_url": "https://twitter.com/netflix/status/1395165585311375360/photo/1",
        "type": "photo",
        "sizes": {
          "small": {
            "w": 680,
            "h": 355,
            "resize": "fit"
          },
          "thumb": {
            "w": 150,
            "h": 150,
            "resize": "crop"
          },
          "medium": {
            "w": 1200,
            "h": 627,
            "resize": "fit"
          },
          "large": {
            "w": 1734,
            "h": 906,
            "resize": "fit"
          }
        }
      },
      {
        "id": 1395165559377981442,
        "id_str": "1395165559377981442",
        "indices": [
          46,
          69
        ],
        "media_url": "http://pbs.twimg.com/media/E1yfrzGVcAIQGcR.jpg",
        "media_url_https": "https://pbs.twimg.com/media/E1yfrzGVcAIQGcR.jpg",
        "url": "https://t.co/9L8tiCY2EU",
        "display_url": "pic.twitter.com/9L8tiCY2EU",
        "expanded_url": "https://twitter.com/netflix/status/1395165585311375360/photo/1",
        "type": "photo",
        "sizes": {
          "small": {
            "w": 680,
            "h": 340,
            "resize": "fit"
          },
          "thumb": {
            "w": 150,
            "h": 150,
            "resize": "crop"
          },
          "large": {
            "w": 1822,
            "h": 912,
            "resize": "fit"
          },
          "medium": {
            "w": 1200,
            "h": 601,
            "resize": "fit"
          }
        }
      }
    ]
  },
  "source": "<a href=\"https://about.twitter.com/products/tweetdeck\" rel=\"nofollow\">TweetDeck</a>",
  "in_reply_to_status_id": null,
  "in_reply_to_status_id_str": null,
  "in_reply_to_user_id": null,
  "in_reply_to_user_id_str": null,
  "in_reply_to_screen_name": null,
  "user": {
    "id": 16573941,
    "id_str": "16573941",
    "name": "Netflix",
    "screen_name": "netflix",
    "location": "California, USA",
    "description": "Meet Asian Americans & Pacific Islanders who are defining their stories \u2014 on their terms \u2014 with this collection https://t.co/2gcE1B3nHk",
    "url": "https://t.co/XzOdAb0vdS",
    "entities": {
      "url": {
        "urls": [
          {
            "url": "https://t.co/XzOdAb0vdS",
            "expanded_url": "http://netflix.com/blacklivesmatter",
            "display_url": "netflix.com/blacklivesmatt\u2026",
            "indices": [
              0,
              23
            ]
          }
        ]
      },
      "description": {
        "urls": [
          {
            "url": "https://t.co/2gcE1B3nHk",
            "expanded_url": "https://www.netflix.com/browse/genre/3137292",
            "display_url": "netflix.com/browse/genre/3\u2026",
            "indices": [
              112,
              135
            ]
          }
        ]
      }
    },
    "protected": false,
    "followers_count": 11891956,
    "friends_count": 1797,
    "listed_count": 17687,
    "created_at": "Fri Oct 03 04:16:17 +0000 2008",
    "favourites_count": 14985,
    "utc_offset": null,
    "time_zone": null,
    "geo_enabled": true,
    "verified": true,
    "statuses_count": 38916,
    "lang": null,
    "contributors_enabled": false,
    "is_translator": false,
    "is_translation_enabled": false,
    "profile_background_color": "C0DEED",
    "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
    "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
    "profile_background_tile": false,
    "profile_image_url": "http://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg",
    "profile_image_url_https": "https://pbs.twimg.com/profile_images/1235992718171467776/PaX2Bz1S_normal.jpg",
    "profile_banner_url": "https://pbs.twimg.com/profile_banners/16573941/1621037719",
    "profile_link_color": "E50914",
    "profile_sidebar_border_color": "FFFFFF",
    "profile_sidebar_fill_color": "DDEEF6",
    "profile_text_color": "333333",
    "profile_use_background_image": false,
    "has_extended_profile": false,
    "default_profile": false,
    "default_profile_image": false,
    "following": false,
    "follow_request_sent": false,
    "notifications": false,
    "translator_type": "none",
    "withheld_in_countries": []
  },
  "geo": null,
  "coordinates": null,
  "place": null,
  "contributors": null,
  "is_quote_status": false,
  "retweet_count": 180,
  "favorite_count": 1868,
  "favorited": false,
  "retweeted": false,
  "possibly_sensitive": false,
  "lang": "en"
}

In [14]:
#For each tweet in the netflix list - print out only the text that correlates 
#Get to understand how the text data looks 
for doc in netflix_list:
    print(doc._json['text'])

Who Killed Sara?

Season 2 is now on Netflix. https://t.co/9L8tiCY2EU
RT @NetflixFilm: getting caught in the rain:
expectation vs. reality https://t.co/WlINcgkn3N
@meg_townsend @Most even her vocal pops in ''Thriller/Heads Will Roll'' are ICONIC
@Most The Troubletones deserved better
@Susy9514 Naya + Grant Gustin -- so good
@PlayzWSquirlz Santana &amp; Mercedes were THEE DUO
Glee premiered 12 years ago today — what’s your favorite performance from the show and why is it Rumour Has It/Someone Like You?
RT @its_willyu: Over The Moon              Wish Dragon

                               🤝

             Animated Netflix movies…
RT @arahir: yes i love all the characters in castlevania. isaac, isaac's demon, isaac's other demon, isaac's demon army, isaac's mirror, is…
Arnold @Schwarzenegger will star in &amp; EP a new series about a father &amp; daughter (Monica Barbaro) who discover they’… https://t.co/d1NWIQHrDE

In [15]:
#For each tweet in our list - print the created_at variable information - this is the date the tweet was posted 

for doc in netflix_list:
    print(doc._json['created_at'])

Wed May 19 23:52:51 +0000 2021
Wed May 19 23:40:26 +0000 2021
Wed May 19 20:38:03 +0000 2021
Wed May 19 20:24:25 +0000 2021
Wed May 19 20:07:48 +0000 2021
Wed May 19 20:06:58 +0000 2021
Wed May 19 20:00:01 +0000 2021
Wed May 19 19:59:38 +0000 2021
Wed May 19 19:53:25 +0000 2021
Wed May 19 19:01:38 +0000 2021

In [16]:
#For each tweet, print out the favorite and retweet counts 
for doc in netflix_list:
    print(doc._json['favorite_count'], doc._json['retweet_count'])

1868 180
0 143
16 0
94 8
1622 96
17 1
16618 2529
0 142
0 92
3078 314

In [17]:
#Import pandas to turn the timeline data into a data frame for further analysis 
import pandas as pd

In [18]:
#Create a netflix tweet list with 600 tweets:
ntweets = api.user_timeline("netflix", count=600)
#Print out the count of the list just created - make sure count is 600
print("Netflix Tweet Count: {}.\n".format(len(ntweets)))

# Print last 10 tweets - make sure they look like the JSON data above - use \n for spaces between lines 
print("Last 10 Netflix Tweets:\n")
for tweet in ntweets[:10]:
    print(tweet.text)
    print()

Netflix Tweet Count: 200.

Last 10 Netflix Tweets:

Who Killed Sara?

Season 2 is now on Netflix. https://t.co/9L8tiCY2EU

RT @NetflixFilm: getting caught in the rain:
expectation vs. reality https://t.co/WlINcgkn3N

@meg_townsend @Most even her vocal pops in ''Thriller/Heads Will Roll'' are ICONIC

@Most The Troubletones deserved better

@Susy9514 Naya + Grant Gustin -- so good

@PlayzWSquirlz Santana &amp; Mercedes were THEE DUO

Glee premiered 12 years ago today — what’s your favorite performance from the show and why is it Rumour Has It/Someone Like You?

RT @its_willyu: Over The Moon              Wish Dragon

                               🤝

             Animated Netflix movies…

RT @arahir: yes i love all the characters in castlevania. isaac, isaac's demon, isaac's other demon, isaac's demon army, isaac's mirror, is…

Arnold @Schwarzenegger will star in &amp; EP a new series about a father &amp; daughter (Monica Barbaro) who discover they’… https://t.co/d1NWIQHrDE

In [20]:
# Print out variables from the first tweet other than text - make sure that information is retrievable 
#For the sake of our questions - won't need any additional variables 

print(ntweets[0].id)
print(ntweets[0].created_at)
print(ntweets[0].source)
print(ntweets[0].favorite_count)
print(ntweets[0].retweet_count)

1395165585311375360
2021-05-19 23:52:51
TweetDeck
1868
180

In [66]:
# The ntweet list has a limit of 200, had to use the cursor method to get our desired 600 tweets 
# Create a pandas data frame to get each text value from each tweet in out the netflix user timeline - label the column as Tweets 
netflix_df = pd.DataFrame(data=[tweet.text for tweet in tweepy.Cursor(api.user_timeline, id="netflix").items(600)], columns=['Tweets'])

# Show the first 10 instances in the data frame to make sure it turned out as intended 
netflix_df.head(10)

                                              Tweets
0  Who Killed Sara?\n\nSeason 2 is now on Netflix...
1  RT @NetflixFilm: getting caught in the rain: \...
2  @meg_townsend @Most even her vocal pops in ''T...
3             @Most The Troubletones deserved better
4           @Susy9514 Naya + Grant Gustin -- so good
5  @PlayzWSquirlz Santana &amp; Mercedes were THE...
6  Glee premiered 12 years ago today — what’s you...
7  RT @its_willyu: Over The Moon              Wis...
8  RT @arahir: yes i love all the characters in c...
9  Arnold @Schwarzenegger will star in &amp; EP a...

In [21]:
#Import numpy so we can add other necessary information to our data frame - have data correlate as intended 
import numpy as np

In [67]:
#Need the Cursor iteration in each np.array so that we can build a data frame with 600 tweets
#Could to "for tweet in ntweets", but would be limited to 200 tweets
#Want several hundred results for deeper analysis 
#User the same calls as listed above - .id, .created_at etc
#Add each as a column in the netflix df 

# Add length variable to the data frame - measures the number of total characters in the text 
netflix_df['len']  = np.array([len(tweet.text) for tweet in tweepy.Cursor(api.user_timeline, id="netflix").items(600)])
# Add ID number to keep track of who made each tweet 
netflix_df['ID']   = np.array([tweet.id for tweet in tweepy.Cursor(api.user_timeline, id="netflix").items(600)])
# Add a Date column to insert the created at values - will be necessary for breakdown of tweets per hour 
netflix_df['Date'] = np.array([tweet.created_at for tweet in tweepy.Cursor(api.user_timeline, id="netflix").items(600)])
# Add source column to understand what medium the tweet was posted from 
netflix_df['Source'] = np.array([tweet.source for tweet in tweepy.Cursor(api.user_timeline, id="netflix").items(600)])
# Add favorites column to keep track of the favorite count for each tweet 
netflix_df['Favs']  = np.array([tweet.favorite_count for tweet in tweepy.Cursor(api.user_timeline, id="netflix").items(600)])
# Add RTs column to keep track of the retweet count for each tweet 
netflix_df['RTs']    = np.array([tweet.retweet_count for tweet in tweepy.Cursor(api.user_timeline, id="netflix").items(600)])

In [68]:
# Show the head of the data frame after adding these new columns 
netflix_df.head(10)

,Tweets,len,ID,Date,Source,Favs,RTs
0,Who Killed Sara?\n\nSeason 2 is now on Netflix...,69,1395165585311375360,2021-05-19 23:52:51,TweetDeck,1933,189
1,RT @NetflixFilm: getting caught in the rain: \...,93,1395162460257087491,2021-05-19 23:40:26,TweetDeck,0,146
2,@meg_townsend @Most even her vocal pops in ''T...,82,1395116562827268101,2021-05-19 20:38:03,TweetDeck,16,0
3,@Most The Troubletones deserved better,38,1395113133748809729,2021-05-19 20:24:25,TweetDeck,98,8
4,@Susy9514 Naya + Grant Gustin -- so good,40,1395108951880912896,2021-05-19 20:07:48,TweetDeck,1658,99
5,@PlayzWSquirlz Santana &amp; Mercedes were THE...,51,1395108743134683136,2021-05-19 20:06:58,TweetDeck,17,1
6,Glee premiered 12 years ago today — what’s you...,128,1395106992264339459,2021-05-19 20:00:01,TweetDeck,16986,2594
7,RT @its_willyu: Over The Moon Wis...,127,1395106896541995008,2021-05-19 19:59:38,TweetDeck,0,143
8,RT @arahir: yes i love all the characters in c...,140,1395105330435133441,2021-05-19 19:53:25,TweetDeck,0,95
9,Arnold @Schwarzenegger will star in &amp; EP a...,148,1395092300951289858,2021-05-19 19:01:38,TweetDeck,3110,316

In [60]:
# Create a data frame for Hulu - start with the column Tweets - and input the text for each tweet 
hulu_df = pd.DataFrame(data=[tweet.text for tweet in tweepy.Cursor(api.user_timeline, id="hulu").items(600)], columns=['Tweets'])

# Show the first 10 instances in the data frame - reference the netflix data frame to make sure everything went correctly 
hulu_df.head(10)

                                              Tweets
0                 @CallofDuty 🔥🔥🔥 #DieHardWatchParty
1  @CallofDuty Louder. I’ve been WAITIN on this o...
2                @LoveVictorHulu it's so beautiful 😭
3  brb, gonna go drape myself in the season 2 #Lo...
4  RT @alwayssunny: This Watch Party is going to ...
5  @CallofDuty My completely irrational fear of e...
6  @CallofDuty Me, audibly: ASDHHKSIFHWU #DieHard...
7  @CallofDuty I love the way you think. #DieHard...
8  @CallofDuty Me @ all my friends the moment we ...
9  @CallofDuty I'm simply @'ing you to agree with...

In [62]:
# Input the same new columns into the Hulu data frame that were inserted into the Netflix data frame - for equal analysis 

hulu_df['len']  = np.array([len(tweet.text) for tweet in tweepy.Cursor(api.user_timeline, id="hulu").items(600)])
hulu_df['ID']   = np.array([tweet.id for tweet in tweepy.Cursor(api.user_timeline, id="hulu").items(600)])
hulu_df['Date'] = np.array([tweet.created_at for tweet in tweepy.Cursor(api.user_timeline, id="hulu").items(600)])
hulu_df['Source'] = np.array([tweet.source for tweet in tweepy.Cursor(api.user_timeline, id="hulu").items(600)])
hulu_df['Favs']  = np.array([tweet.favorite_count for tweet in tweepy.Cursor(api.user_timeline, id="hulu").items(600)])
hulu_df['RTs']    = np.array([tweet.retweet_count for tweet in tweepy.Cursor(api.user_timeline, id="hulu").items(600)])

In [63]:
#Show the first 10 instances in the Hulu data frame with these new variables 

hulu_df.head(10)

,Tweets,len,ID,Date,Source,Favs,RTs
0,@CallofDuty 🔥🔥🔥 #DieHardWatchParty,34,1395216496549376002,2021-05-20 03:15:09,Twitter for iPhone,7,1
1,@CallofDuty Louder. I’ve been WAITIN on this o...,68,1395214868660297731,2021-05-20 03:08:41,Twitter for iPhone,1,0
2,@LoveVictorHulu it's so beautiful 😭,35,1395212870829297665,2021-05-20 03:00:44,Twitter Web App,117,7
3,"brb, gonna go drape myself in the season 2 #Lo...",85,1395212685592219650,2021-05-20 03:00:00,Sprinklr,274,50
4,RT @alwayssunny: This Watch Party is going to ...,140,1395212622782353409,2021-05-20 02:59:45,Twitter Web App,0,15
5,@CallofDuty My completely irrational fear of e...,82,1395203136059592704,2021-05-20 02:22:03,Twitter for iPhone,6,0
6,"@CallofDuty Me, audibly: ASDHHKSIFHWU #DieHard...",56,1395202938235203587,2021-05-20 02:21:16,Twitter for iPhone,8,0
7,@CallofDuty I love the way you think. #DieHard...,56,1395199198467866625,2021-05-20 02:06:25,Twitter Web App,13,0
8,@CallofDuty Me @ all my friends the moment we ...,90,1395197772027072515,2021-05-20 02:00:45,Twitter Web App,10,0
9,@CallofDuty I'm simply @'ing you to agree with...,70,1395192128213561345,2021-05-20 01:38:19,Twitter Web App,25,0

In [64]:
# Get summary statistics about the length, favorites, and retweets for Hulu
#Store in data frame variable for comparison 
hulustats= pd.DataFrame(hulu_df.describe())

In [69]:
# Get the summary statistics about lenght, favorites, and retweets for Netflix
#Store in data frame variable for comparison 
netflixstats= pd.DataFrame(netflix_df.describe())

In [120]:
#Create new file with this summary data
#Use the .compare function to compare the two summary statistic data frames - keep the same shape, and keep the values that are equal
statscompare = hulustats.compare(netflixstats,keep_shape=True, keep_equal=True) 
#So that this is not confusing on a new csv, change the self stats to be labeled Hulu, and other to be labeled Netflix
statscompare = statscompare.rename(columns={"self": "Hulu", "other": "Netflix"})
#Create the first file output for our analysis 
statscompare.to_csv('statscompare.csv')

In [71]:
# Question 1:  How do the likes, retweet , and length statistics compare between the most recent 600 tweets?
    # Units of analysis - likes, retweets, text character length 
statscompare

              len                        ID                       Favs  \
             Hulu     Netflix          Hulu       Netflix         Hulu
count  600.000000  600.000000  6.000000e+02  6.000000e+02   600.000000
mean    47.561667  107.543333  1.394031e+18  1.388811e+18    38.786667
std     27.435087   36.758129  8.305169e+14  4.109905e+15   319.098126
min      5.000000   12.000000  1.392555e+18  1.380193e+18     0.000000
25%     31.000000   82.000000  1.393285e+18  1.385643e+18     0.000000
50%     40.000000  120.000000  1.394077e+18  1.389228e+18     1.000000
75%     53.000000  140.000000  1.394746e+18  1.392549e+18     4.000000
max    144.000000  148.000000  1.395216e+18  1.395166e+18  7168.000000

                              RTs
            Netflix          Hulu        Netflix
count    600.000000    600.000000     600.000000
mean    1703.541667     29.755000    1061.040000
std     4145.381837    459.207329    6257.508164
min        0.000000      0.000000       0.000000
25%        0.000000      0.000000      45.000000
50%        0.000000      0.000000     159.000000
75%     1559.000000      1.000000     532.500000
max    42409.000000  11021.000000  117652.000000

In [32]:
# Question 1 Answer: 
    #Hulu on average has a tweet length of 47.5 characters, 38.7 likes per tweet, and 29.7 retweets per tweet 
    #Netflix on average has a tweet length of 107.5 characters, 1703.5 likes per tweet, and 1061 retweets per tweet 
    #Hulu has a Max length of 144, max favorite count of 7168, and max retweet count of 11021
    #Netflix has a max length of 148, max favorite count of 42409, and max retweet count of 117652
    
    #It seems as though overall, Netflix has a more engaging twitter platform than Hulu based off of the last 600 tweets 
    #Netflix also seems to have longer tweets - this could play into the higher mean and max values for their RTs and Favs

In [72]:
#Import datetime so that we can do analysis on when tweets were created 
from datetime import datetime

In [73]:
#Create a convert date function to take the Date data -and convert to datetime object 
#Need to nest the date in str() to make it a string - right now it is a timestamp 
def convert_date(date):
    """
    Takes date as string
    Returns date as datetime.datetime object
    """
    return datetime.strptime(str(date), '%Y-%m-%d %H:%M:%S')

In [74]:
#Apply function to every tweet in the date column in the netflix dataframe 
netflix_df['Date'] = netflix_df['Date'].apply(lambda x: convert_date(x))

In [75]:
#Apply function to every tweet in the date column in the hulu dataframe 
hulu_df['Date'] = hulu_df['Date'].apply(lambda x: convert_date(x))

In [78]:
#Create bins - iterate by 1 from the range 0-24
#Must make the range 25, or times in between 23-24 hours will be left out 
bins = [x for x in range (0,25,1)]
bins


# Add these new bins to our netflix data frame 
#In the data frame - use cut function on Date to only target the hour 
#create new column called Time Bin - the hour will categorize which bin this is in 
netflix_df['Time Bin'] = pd.cut(netflix_df.Date.dt.hour, bins, right=False)

#Repeat for hulu data frame 
hulu_df['Time Bin'] = pd.cut(hulu_df.Date.dt.hour, bins, right=False)

In [79]:
#Show the first 10 rows of the netflix data frame - ensure that the code works 
netflix_df.head(10)

,Tweets,len,ID,Date,Source,Favs,RTs,Time Bin
0,Who Killed Sara?\n\nSeason 2 is now on Netflix...,69,1395165585311375360,2021-05-19 23:52:51,TweetDeck,1933,189,"[23, 24)"
1,RT @NetflixFilm: getting caught in the rain: \...,93,1395162460257087491,2021-05-19 23:40:26,TweetDeck,0,146,"[23, 24)"
2,@meg_townsend @Most even her vocal pops in ''T...,82,1395116562827268101,2021-05-19 20:38:03,TweetDeck,16,0,"[20, 21)"
3,@Most The Troubletones deserved better,38,1395113133748809729,2021-05-19 20:24:25,TweetDeck,98,8,"[20, 21)"
4,@Susy9514 Naya + Grant Gustin -- so good,40,1395108951880912896,2021-05-19 20:07:48,TweetDeck,1658,99,"[20, 21)"
5,@PlayzWSquirlz Santana &amp; Mercedes were THE...,51,1395108743134683136,2021-05-19 20:06:58,TweetDeck,17,1,"[20, 21)"
6,Glee premiered 12 years ago today — what’s you...,128,1395106992264339459,2021-05-19 20:00:01,TweetDeck,16986,2594,"[20, 21)"
7,RT @its_willyu: Over The Moon Wis...,127,1395106896541995008,2021-05-19 19:59:38,TweetDeck,0,143,"[19, 20)"
8,RT @arahir: yes i love all the characters in c...,140,1395105330435133441,2021-05-19 19:53:25,TweetDeck,0,95,"[19, 20)"
9,Arnold @Schwarzenegger will star in &amp; EP a...,148,1395092300951289858,2021-05-19 19:01:38,TweetDeck,3110,316,"[19, 20)"

In [80]:
#Show the first 10 rows of the hulu data frame - ensure that the code works 
hulu_df.head(10)

,Tweets,len,ID,Date,Source,Favs,RTs,Time Bin
0,@CallofDuty 🔥🔥🔥 #DieHardWatchParty,34,1395216496549376002,2021-05-20 03:15:09,Twitter for iPhone,7,1,"[3, 4)"
1,@CallofDuty Louder. I’ve been WAITIN on this o...,68,1395214868660297731,2021-05-20 03:08:41,Twitter for iPhone,1,0,"[3, 4)"
2,@LoveVictorHulu it's so beautiful 😭,35,1395212870829297665,2021-05-20 03:00:44,Twitter Web App,117,7,"[3, 4)"
3,"brb, gonna go drape myself in the season 2 #Lo...",85,1395212685592219650,2021-05-20 03:00:00,Sprinklr,274,50,"[3, 4)"
4,RT @alwayssunny: This Watch Party is going to ...,140,1395212622782353409,2021-05-20 02:59:45,Twitter Web App,0,15,"[2, 3)"
5,@CallofDuty My completely irrational fear of e...,82,1395203136059592704,2021-05-20 02:22:03,Twitter for iPhone,6,0,"[2, 3)"
6,"@CallofDuty Me, audibly: ASDHHKSIFHWU #DieHard...",56,1395202938235203587,2021-05-20 02:21:16,Twitter for iPhone,8,0,"[2, 3)"
7,@CallofDuty I love the way you think. #DieHard...,56,1395199198467866625,2021-05-20 02:06:25,Twitter Web App,13,0,"[2, 3)"
8,@CallofDuty Me @ all my friends the moment we ...,90,1395197772027072515,2021-05-20 02:00:45,Twitter Web App,10,0,"[2, 3)"
9,@CallofDuty I'm simply @'ing you to agree with...,70,1395192128213561345,2021-05-20 01:38:19,Twitter Web App,25,0,"[1, 2)"

In [121]:
#Group the dataframe by the Time Bins, and then return the count of occurrences for each time bin
#This will show how many tweets were created within that binned hour 
netflixph = netflix_df.groupby(['Time Bin'])['Time Bin'].count()

#Return to console to ensure the frequency was recorded correctly 
netflixph

Time Bin
[0, 1)      16
[1, 2)      18
[2, 3)       5
[3, 4)       4
[4, 5)       6
[5, 6)       2
[6, 7)       0
[7, 8)       1
[8, 9)       0
[9, 10)      0
[10, 11)     0
[11, 12)     0
[12, 13)     0
[13, 14)    17
[14, 15)    44
[15, 16)    46
[16, 17)    65
[17, 18)    66
[18, 19)    53
[19, 20)    65
[20, 21)    53
[21, 22)    55
[22, 23)    51
[23, 24)    33
Name: Time Bin, dtype: int64

In [82]:
#Put this into a data frame 
nfph = pd.DataFrame(netflixph)

#Rename the time bin column to Netflix Tweets Per Hour 
#This will make analysis easier in the newly exported file
nfph = nfph.rename(columns={"Time Bin": "Netflix Tweets Per Hour"})

In [83]:
#Repeat the process for Hulu
huluph = hulu_df.groupby(['Time Bin'])['Time Bin'].count()
print(huluph)

Time Bin
[0, 1)      217
[1, 2)       25
[2, 3)        6
[3, 4)        5
[4, 5)        2
[5, 6)        0
[6, 7)        0
[7, 8)        0
[8, 9)        0
[9, 10)       0
[10, 11)      0
[11, 12)      0
[12, 13)      0
[13, 14)      0
[14, 15)      4
[15, 16)     10
[16, 17)      1
[17, 18)     34
[18, 19)     56
[19, 20)    110
[20, 21)     34
[21, 22)     24
[22, 23)      7
[23, 24)     65
Name: Time Bin, dtype: int64

In [84]:
#Put the new grouped data into a dataframe 
hfph = pd.DataFrame(huluph)

#Rename the time bin column to make analysis easy 
hfph = hfph.rename(columns={"Time Bin": "Hulu Tweets Per Hour"})

In [85]:
#Create a variable that has both data frames stored 
perhour_dfs = [nfph, hfph]
#concatenate the data frames on a single axis, inner join so that they are compared at each bin
perhourcompare = pd.concat(perhour_dfs, axis=1, join='inner')
#Create output file number 2 
perhourcompare.to_csv('perhourcompare.csv')

In [86]:
#Return to console to ensure that the output looks how it is intended 
perhourcompare

          Netflix Tweets Per Hour  Hulu Tweets Per Hour
Time Bin
[0, 1)                         16                   217
[1, 2)                         18                    25
[2, 3)                          5                     6
[3, 4)                          4                     5
[4, 5)                          6                     2
[5, 6)                          2                     0
[6, 7)                          0                     0
[7, 8)                          1                     0
[8, 9)                          0                     0
[9, 10)                         0                     0
[10, 11)                        0                     0
[11, 12)                        0                     0
[12, 13)                        0                     0
[13, 14)                       17                     0
[14, 15)                       44                     4
[15, 16)                       46                    10
[16, 17)                       65                     1
[17, 18)                       66                    34
[18, 19)                       53                    56
[19, 20)                       65                   110
[20, 21)                       53                    34
[21, 22)                       55                    24
[22, 23)                       51                     7
[23, 24)                       33                    65

In [46]:
#Question 2: Of the last 600 tweets, how does the tweet distribution per hour differ between the two?
    #Unit of analysis - Hour of day

In [47]:
#Question 2 Answer:
    #Based on the last 600 tweets, Hulu seems to be tweeting more consistently at night - hour 17 (5pm) until hour 2 (2am)
        #With the exception of hour 22 (10pm), the tweets were most prevalent in this time frame 
        #They additionally tweeted 217 times from 12-1am, and 110 times from 7-8pm
        #This is where the bulk of there 600 tweets come from, extremely concentrated activity times
        
    #For Netflix they seem to have much more even distribution and consistency
        #From hour 13 (1pm) until hour 2 (2am) they have a fairly consistent flow of tweets
        #They have consistent tweet counts from hour 14 (2pm) until hour 23 (11pm)
        #The overall consistency and activity during these day hours could contribute to their favorable engagement numbers 
        
    #Both are fairly quiet during the morning hours - from hour 3 (3am) until hour 13 (1pm), it is fairly dead on both ends
    #Netflix seems to know when twitter users will be active, and may have a method of content rollout at high activity times
    #the morning hours most likely don't have many active users - both companies probably know that 
        #save their content for when more users may see it

In [105]:
#Create a new groupby, group the data frame by the source data
#Use .agg to use multiple aggregate functions in this one groupby formula
#Want the tweet count for each source, and the Fav/RT statistics for each
netflixs = netflix_df.groupby(['Source']).agg({'RTs': ['mean', 'min', 'max'], 'Favs': ['mean', 'min', 'max'], 'Source': ['count']})
#Return output to console 
netflixs

                              RTs                     Favs             Source
                             mean min     max         mean  min    max  count
Source
TweetDeck              784.813559   0   32586  1463.008475    0  42409    236
Twitter Media Studio   637.594059  34    5359  3906.069307  636  25192    101
Twitter Web App       1311.657534   0   69902  1151.691781    0  30368    146
Twitter for iPhone    1671.017094   0  117652   976.025641    0  20327    117

In [106]:
#Repeat this process for Hulu
hulus = hulu_df.groupby(['Source']).agg({'RTs': ['mean', 'min', 'max'], 'Favs': ['mean', 'min', 'max'], 'Source': ['count']})
hulus

                           RTs                   Favs           Source
                          mean min    max        mean min   max  count
Source
Sprinklr             26.272727   1    181  231.969697  25  1233     33
Twitter Web App       3.088512   0    405   14.661017   0  2008    531
Twitter for iPhone  426.277778   0  11021  217.555556   0  7168     36

In [118]:
#Create a comparison variable that will compare both source stats for Hulu and netflix
#Concatenate the two data frames on the 0 Axis, inner join so that the RTs, Favs, and Source are not duplicated 
#List the keys to be Netflix and Hulu so that identifying each data set is easier 
sourcecompare = pd.concat([netflixs, hulus], axis=0, join="inner", keys=['Netflix', 'Hulu'])
#Create the file output 3 for analysis 
sourcecompare.to_csv('sourcecompare.csv')

In [119]:
#Return output to the console 
sourcecompare
#This data frame compares the tweet sources for each company, and breaks down the use frequency, and then engagement stats

                                      RTs                     Favs       \
                                     mean min     max         mean  min
        Source
Netflix TweetDeck              784.813559   0   32586  1463.008475    0
        Twitter Media Studio   637.594059  34    5359  3906.069307  636
        Twitter Web App       1311.657534   0   69902  1151.691781    0
        Twitter for iPhone    1671.017094   0  117652   976.025641    0
Hulu    Sprinklr                26.272727   1     181   231.969697   25
        Twitter Web App          3.088512   0     405    14.661017    0
        Twitter for iPhone     426.277778   0   11021   217.555556    0

                                    Source
                                max  count
        Source
Netflix TweetDeck             42409    236
        Twitter Media Studio  25192    101
        Twitter Web App       30368    146
        Twitter for iPhone    20327    117
Hulu    Sprinklr               1233     33
        Twitter Web App        2008    531
        Twitter for iPhone     7168     36

In [ ]:
#Question 3: How does the source of tweet creation differ between the two? What does distribution looks like, and how does engagement correlate?
    #Unit of analysis: Source of tweet

In [ ]:
#Question 3 Answer:
    #Based on the last 600 tweets, it is clear that their distribution of tweets through sources differ
    #Hulu uses a source called Sprinklr, and Netflix doesn't
    #Netflix uses two sources that Hulu doesn't - TweetDeck, and Twitter Media Studio
    
    #It seems as though Hulu tweets heavily concentrated through the Twitter Web App 
        #Averages - 3 Rts, 14 Favs
        #Maxs - 405 Rts, 2008 Favs 
        #This high ferquency tweeting could be solely to reply - that is why engagement could be low
    #Hulu seems to get their best engagement stats through Twitter for iPhone, but a miniscule amount of tweets are created here
        #Averages - 426 Rts, 217 Favs
        #Maxs - 11021 Rts, 7168 Favs
        #This could be where their best work is formed, so lower frequency
        
    #Netflix seems to have a heavier concentration on TweetDeck, but is fairly evenly distributed 
        #Averages - 784 Rts, 1463 Favs
        #Maxs - 32586 Rts, 42409 Favs
        #These are good number, it makes sense why focus would be through this source
    #The other netflix numbers are still great 
        #Twitter media studio has the least frequency of tweets, but the highest average for favorites
        #Min values for RTs and Favs for Twitter Media Studio should also be noted, it is not zero - and is fairly high 
        #Maybe they take their time to create quality tweets through this source
        
    #Sources differ between the two companies, and tweet creation amongst those sources differs as well 
    #There are clearly sources that are more favored at each company
    #And there are some sources that have higher engagement numbers
    #It seems as thought both companies do well in terms of engagement through their twitter for iphone source
    #Netflix favors TweetDeck, and Hulu favors the Twitter Web App
    #Both companies must use their sources strategically